### ISSUE TITLE
clang++ exited with code 1: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by DmitryNikiforovCoherent** [alexanderdibenedetto/trustkit-xamarin-bindings#14]
Trying on Mac with M chip. Have build error with logs
  Xamarin.Shared.Sdk.targets(1641, 3): clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TSKPinningValidator", referenced from:
     -exported_symbol[s_list] command line option
  "_OBJC_CLASS_$_TSKPinningValidatorResult", referenced from:
     -exported_symbol[s_list] command line option
  "_OBJC_CLASS_$_TrustKit", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alexanderdibenedetto** [comment]
I'll update the TrustKit.framework to a .xcframework in the next release so you can use it on iOS Simulator also! Thanks for reporting.
